### ISSUE TITLE
Windows Server 2012 R3 Standard - numexpr module

### ISSUE THREAD

**Issue by dimmichel** [KrisHammerberg/DEMtools#4]
Hi,

Thanks for all the effort and time that you have put in this plugin.

I am getting an error message after installing the DEMtools plugin in QGIS 2.6 - Brighton.

The error message is the following:
An error message The plugin is broken, Python said:
No Module named numexpr

Should you include this module in the next version or is there a way to do this myself?

Regards
D.

**Comment by KrisHammerberg** [comment]
numexpr is a module that allows multicore processing of numpy array operations. Find out more here: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide

For now you'll have to install it yourself, but its a useful tool if you are dealing with large array operations in Python. :)

**Comment by KrisHammerberg** [comment]
Missing module, but should be fairly standard for those involved with scientific computing .
