### ISSUE TITLE
Please add more description to the About

### ISSUE THREAD

**Issue by pcav** [KrisHammerberg/DEMtools#6]
So a new user can understand what is this useful for.

**Comment by KrisHammerberg** [comment]
Description added.

On Thu, Mar 24, 2016 at 11:45 AM, Paolo Cavallini <notifications@github.com>
wrote:

> So a new user can understand what is this useful for.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KrisHammerberg/DEMtools/issues/6>
>



-- 
Kris Hammerberg, MS
PhD candidate
Department of Building Physics and Building Ecology
Department of Spatial Planning
Vienna University of Technology
Austria

**Comment by pcav** [comment]
Thanks!
